### ISSUE TITLE
The more links are not working

### ISSUE THREAD

**Issue by FlorianBrinkmann** [aarongustafson/mactowindows.com#3]
Hi!

I am not familar with Jekyll, so can not create a PR for this… After clicking on »More Opinions & Reactions« or »More Development«, I get an error that there are no resources in this section.

**Comment by aarongustafson** [comment]
They are working now. I had a plugin issue (as in, I wrote a plugin and it wasn’t working ;-))

**Comment by FlorianBrinkmann** [comment]
:D great, thank you!
