### ISSUE TITLE
SSL Certificate Invalid

### ISSUE THREAD

**Issue by martinwolf** [aarongustafson/mactowindows.com#7]
Hey,

seems like the SSL certificate is invalid:

![screen shot 2018-05-14 at 13 39 25](https://user-images.githubusercontent.com/1442939/39995427-6fef845e-577c-11e8-9b58-baa3d29978af.png)

Cheers,
Martin

**Comment by aarongustafson** [comment]
Bah, LetsEncrypt + Azure is not always happy. I'll look at the cron log.

**Comment by aarongustafson** [comment]
Azure finally allows for non-expiring client secrets, so this is working again.
